export const COLLECTION_IMAGES = [
    { label: "Bunnies", image: require('@/assets/images/bunnies-categories.png') },
    { label: "Bears", image: require('@/assets/images/bears-categories.png') },
    { label: "Amuseables", image: require('@/assets/images/amuseables-categories.png') },
    { label: "Bashfuls", image: require('@/assets/images/bashfuls-categories.png') },
    { label: "Nature", image: require('@/assets/images/nature-categories.png') },
    { label: "Sea Creatures", image: require('@/assets/images/sea-creatures-categories.png') },
    { label: "Accessories", image: require('@/assets/images/accessories-categories.jpg') },
    { label: "Around the Home", image: require('@/assets/images/around-the-home-categories.jpg') },
    { label: "Baby", image: require('@/assets/images/baby-categories.jpg') },
    { label: "Bashful Bunnies", image: require('@/assets/images/bashful-bunnies-categories.jpg') },
    { label: "Birds", image: require('@/assets/images/birds-categories.jpg') },
    { label: "Blossoms", image: require('@/assets/images/blossoms-categories.jpg') },
    { label: "Bugs", image: require('@/assets/images/bugs-categories.jpg') },
    { label: "Cats", image: require('@/assets/images/cats-categories.jpg') },
    { label: "Cordy Roy", image: require('@/assets/images/cordy-roy-categories.jpg') },
    { label: "Desert", image: require('@/assets/images/desert-categories.jpg') },
    { label: "Dinosaurs", image: require('@/assets/images/dinosaurs-categories.jpg') },
    { label: "Dogs", image: require('@/assets/images/dogs-categories.jpg') },
    { label: "Farmyard", image: require('@/assets/images/farmyard-categories.jpg') },
    { label: "Food", image: require('@/assets/images/food-categories.jpg') },
    { label: "Freshwater Animals", image: require('@/assets/images/freshwater-animals-categories.jpg') },
    { label: "Fuddlewuddle", image: require('@/assets/images/fuddlewuddle-categories.jpg') },
    { label: "Halloween", image: require('@/assets/images/halloween-categories.jpg') },
    { label: "Jungle", image: require('@/assets/images/jungle-categories.jpg') },
    { label: "Mythical Creatures", image: require('@/assets/images/mythical-creatures-categories.jpg') },
    { label: "Little Critters", image: require('@/assets/images/little-critters-categories.jpg') },
    { label: "Reptiles", image: require('@/assets/images/reptiles-categories.jpg') },
    { label: "Seaside", image: require('@/assets/images/seaside-categories.jpg') },
    { label: "Space", image: require('@/assets/images/space-categories.jpg') },
    { label: "Special Edition Bunnies", image: require('@/assets/images/special-edition-bunnies-categories.jpg') },
    { label: "Sports", image: require('@/assets/images/sports-categories.jpg') },
    { label: "Summer", image: require('@/assets/images/summer-categories.jpg') },
    { label: "Valentines Day", image: require('@/assets/images/valentines-day-categories.jpg') },
    { label: "Winter", image: require('@/assets/images/winter-categories.jpg') },
    { label: "Woodland", image: require('@/assets/images/woodland-categories.jpg') }
];